### ISSUE TITLE
Upload to gh-pages is broken

### ISSUE THREAD

**Issue by pierre-rouanet** [poppy-project/poppy-docs#53]
There seems to be some authentification issue that prevents the doc to be uploaded to gh-pages.

https://travis-ci.org/poppy-project/poppy-docs/builds/108854664

**Comment by ghost** [comment]
@show0k did regenerating the key fix the issue? I used the travis gem to encrypt the env var (key generated with with the poppy bot account), and it used to work.
Are there some settings to use for this to work?

**Comment by show0k** [comment]
No this didn't fix the issue. I encrypted a new token. The error changed a bit but still doesn't work.
