### ISSUE TITLE
Inconsistent structure of the doc

### ISSUE THREAD

**Issue by show0k** [poppy-project/poppy-docs#54]
The tree view of folders are not consistent in the folder tree structure, in the rended HTML and in the pdf which is very confusing....
![html](https://cloud.githubusercontent.com/assets/3891499/13061352/e378ca90-d437-11e5-879f-f63cba09b95f.png)
![pdf](https://cloud.githubusercontent.com/assets/3891499/13061355/e5899c38-d437-11e5-9f64-23812df5334c.png)
![folder_tree](https://cloud.githubusercontent.com/assets/3891499/13061358/e76ee846-d437-11e5-838a-ccf7f674edbc.png)

**Comment by pierre-rouanet** [comment]
They are not built from the same commit apparently. So I guess it's a CI issue.

**Comment by show0k** [comment]
They are all built from the same source on my own computer.

**Comment by show0k** [comment]
Fixed with gitbook
