### ISSUE TITLE
have a look at gitbook usefull extensions

### ISSUE THREAD

**Issue by show0k** [poppy-project/poppy-docs#56]
Some interesting extensions :
- Select version of doc https://plugins.gitbook.com/plugin/versions 
- Use external js and css (same as the front website) https://plugins.gitbook.com/plugin/addcssjs
- Interractive exercise : https://plugins.gitbook.com/plugin/exercises
- integration of retina.js (for Pierre) https://plugins.gitbook.com/plugin/retina
- Numbered headings for GitBook PDFs https://plugins.gitbook.com/plugin/numbered-headings

**Comment by ghost** [comment]
Shout-out to new toys.

![shoulder_shake](https://cloud.githubusercontent.com/assets/37416/13077893/fc2505f2-d4bb-11e5-9d8f-9b3709a24f29.gif)
