### ISSUE TITLE
Add the links for the images download

### ISSUE THREAD

**Issue by sbihel** [poppy-project/poppy-docs#58]
The links only direct to TODO anchors
For example: https://poppy-project.github.io/poppy-docs/#download-the-image

cc @mquinson

**Comment by mquinson** [comment]
Just to be clear, we are speaking of the iso images that must be uploaded to the controler card, not of the lolcat gifs. We do have the later ones, thanks.

**Comment by pierre-rouanet** [comment]
I've just added the image for the Torso: https://github.com/poppy-project/poppy-docs/commit/8e934103f5e5ebab65c38854bbab223b59f75049
I will upload the one for the Humanoid tomorrow. In the mean time, you can show me those locate gifs :smile: 

BTW, the doc has been migrated to: http://docs.poppy-project.org

**Comment by mquinson** [comment]
Sure : http://cheezburger.com/7913549056 http://cheezburger.com/7847858176

You're welcome.
Mt

**Comment by pierre-rouanet** [comment]
Both images have been uploaded. Thanks again for the :cat:
