### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by ghost** [poppy-project/poppy-docs#61]
In "Assembly guide for the Ergo Jr", the Bill of materials has the line "1x disk_support.stl (using laser cutting) the 2D plan can be found here." But "here" is a dead link (https://github.com/poppy-project/poppy-ergo-jr/tree/PR_release_hardware/hardware/laser_cutting)

**Comment by show0k** [comment]
Thanks, it is now [fixed](https://github.com/poppy-project/poppy-ergo-jr/commit/2eaad77e6ff0352eb4bc163bd5862b14e950e92d), you should see it online at the next build.
