### ISSUE TITLE
Traduire les instructions d'assemblage Ergo Jr en Francais

### ISSUE THREAD

**Issue by bcopy** [poppy-project/poppy-docs#73]

**Comment by bcopy** [comment]
I'm currently looking into it, please get in touch with suggestions.

**Comment by show0k** [comment]
We have a proper tool to manage translation now !
Anybody can register and join the translation process: https://crowdin.com/project/poppy-docs

**Comment by show0k** [comment]
The french translation from crowdin is now included !
Thank you for the contribution !
