### ISSUE TITLE
Rivets specified in Ergo Jr. BOM are incorrect.

### ISSUE THREAD

**Issue by Jonathon-RINC** [poppy-project/poppy-docs#99]
The listed BOM for the Ergo Jr. arm includes:
* 1x bag of OLLO rivets (about 70 colored and 4 grey)
* 1x OLLO tool: made to clip and unclip rivets

The OLLO rivets and corresponding tool indicated is this set of [set of 12mm rivets](https://www.robotis.us/l-rivet-set-rs-70/?_ga=2.124033801.2038606284.1655142613-1719310268.1645826640). 

The actual rivets used in the kit are [these 6mm rivets](https://www.robotis.us/rivet-set-rs-10/?_ga=2.199129004.2038606284.1655142613-1719310268.1645826640).

**Comment by ymollard** [comment]
Does the term "OLLO" refer to the 12mm ones? Is there a reference similar to "OLLO" that match the 6mm rivets and tool? Maybe RS-10?

Would you mind making a PR with a proposed correction? You can also include links to Robotis but product pages are preferred to shopping pages.

**Comment by Jonathon-RINC** [comment]
Yoan,

The OLLO product refers to the 12mm rivet size. In the past there was an
OLLO kit that did utilize the 6mm rivets, but that particular product has
been renamed specifically to remove confusion regarding having two
different sized rivets in kits with similar names. The likely reason for
this documentation issue is just that It hasn't been updated since the kit
name change. The products that include the 6mm rivet size used by the Ergo
Jr. are the PLAY, DREAM, and MINI educational kits.

ROBOTIS does not maintain any product detail pages for the rivets
specifically, and there aren't many other places to order just the
rivets/tool. It seems that linking directly to the store pages for the RS-10
<https://www.robotis.us/rivet-set-rs-10/>, MINI
<https://www.robotis.us/robotis-mini-rivet-set/> (Slightly stronger clear
rivets), and rivet tool <https://www.robotis.us/tool-stl/> pages would be
the best option.

I opened the issue rather than submit my own PR to avoid having to clone
the repo to submit only a two line change, I had hoped that a maintainer
that already had the repo available would be able to make the simple
changes and submit this. I can do so if needed, but would prefer not to.

*Thank you,*
*Jonathon*

*ROBOTIS **Technical Specialist / STEAM Consultant*
*(*
***@***.*** ***@***.***>) *
For general & technical support visit Community.Robotis.Us
<http://community.robotis.us>
*Leave us a Google Review here! <https://g.page/RobotisAmerica/review?rc> *Tell
us how we're doing- what do you love, and what can we do better? Leave us a
review or email our team!
<http://www.robotis.us/>
<https://twitter.com/ROBOTISAmerica>
<https://www.facebook.com/RobotisAmerica/>
<https://www.linkedin.com/company/3156709/>
<https://www.youtube.com/robotisamerica> <https://github.com/ROBOTIS-GIT/>
<https://www.reddit.com/r/DYNAMIXEL/>

**Comment by ymollard** [comment]
Thank you Jonathon, this is now fixed in https://github.com/poppy-project/poppy-docs/commit/789c0a47a4b98e6cd1d8246491ac0b45c10bc2e4 and updated online.
